# Generated by Django 4.2.3 on 2023-07-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('ms_code', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Medical service code')),
                ('name', models.CharField(max_length=500, verbose_name='Medical service name')),
                ('rel', models.IntegerField(verbose_name='Sign of relevance')),
                ('dateout', models.DateField(verbose_name='Date out')),
            ],
            options={
                'verbose_name': 'Medical service',
                'verbose_name_plural': 'Medical services',
                'ordering': ['ms_code'],
                'indexes': [models.Index(fields=['name'], name='med_ser__name__idx')],
            },
        ),
    ]
