# Generated by Django 4.2.3 on 2023-07-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_medicalorganization_diagnosis_dia__name__idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEMD2',
            fields=[
                ('internal_message_id', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='Structured Electronic Medical Document identifier')),
                ('sms_profile', models.CharField(max_length=10, verbose_name='Structured Electronic Medical Document profile')),
                ('date_time_create', models.DateTimeField(verbose_name='Date time create')),
                ('patient_snils', models.CharField(max_length=11, verbose_name='Patient SNILS')),
                ('patient', models.CharField(max_length=255, verbose_name='Patient name')),
                ('patient_gender', models.CharField(max_length=7, verbose_name='Patient gender')),
                ('patient_birthday', models.DateField(verbose_name='Patient birthday')),
                ('mo', models.CharField(blank=True, max_length=35, null=True, verbose_name='Medical organization code')),
                ('doctor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Doctor name')),
                ('doctor_job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Doctor job title')),
                ('diagnosis', models.CharField(blank=True, max_length=150, null=True, verbose_name='Doctor job title')),
                ('service', models.CharField(blank=True, max_length=25, null=True, verbose_name='Medical service code')),
                ('service_time', models.DateTimeField(verbose_name='Medical service date time')),
                ('res_protocol', models.CharField(blank=True, null=True, verbose_name='Result protocol')),
                ('res_conclusion', models.CharField(blank=True, null=True, verbose_name='Result conclusion')),
                ('res_recommendation', models.CharField(blank=True, null=True, verbose_name='Result recommendation')),
                ('condition', models.CharField(blank=True, max_length=25, null=True, verbose_name='Condition')),
                ('med_card_amb', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ambulatory medical file')),
                ('med_card_sta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stationary medical file')),
            ],
            options={
                'verbose_name': 'SEMD 2',
                'verbose_name_plural': 'SEMD 2',
                'ordering': ['date_time_create'],
                'indexes': [models.Index(fields=['date_time_create'], name='semd2__date_time_create__idx')],
            },
        ),
    ]
