# Generated by Django 4.2.3 on 2023-07-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_semd2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semd2',
            name='patient_birthday',
        ),
        migrations.AddField(
            model_name='semd2',
            name='patient_birthday_str',
            field=models.CharField(default=20230101, max_length=8, verbose_name='Patient birthday'),
            preserve_default=False,
        ),
    ]
