# Generated by Django 4.2.3 on 2023-07-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_semd2_patient_birthday_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SEMD2',
        ),
    ]
