# Generated by Django 4.2.3 on 2023-07-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_semd2'),
    ]

    operations = [
        migrations.AddField(
            model_name='semd2',
            name='diagnosis_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semd2', to='backend.diagnosis', verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='semd2',
            name='medical_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semd2', to='backend.medicalorganization', verbose_name='Medical organization'),
        ),
        migrations.AddField(
            model_name='semd2',
            name='medical_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semd2', to='backend.medicalservice', verbose_name='Medical service'),
        ),
        migrations.AlterField(
            model_name='semd2',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Diagnosis code'),
        ),
    ]
