# Generated by Django 4.2.3 on 2023-07-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_semd2_diagnosis_1_semd2_medical_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semd2',
            name='diagnosis_1',
        ),
    ]
