# Generated by Django 4.2.3 on 2023-07-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_diagnosis_semd2_diagnoses'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryTest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Laboratory test code')),
                ('name', models.CharField(max_length=300, verbose_name='Laboratory test name')),
                ('eng_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Laboratory test english name')),
                ('short_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Laboratory test short name')),
                ('group_tests', models.CharField(blank=True, max_length=100, null=True, verbose_name='Group tests name')),
                ('mkb10_codes', models.CharField(blank=True, max_length=300, null=True, verbose_name='Medical service codes')),
            ],
            options={
                'verbose_name': 'Laboratory test',
                'verbose_name_plural': 'Laboratory tests',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['name'], name='lab_tes__name__idx')],
            },
        ),
    ]
