# Generated by Django 4.2.3 on 2023-07-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_laboratorytest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('snils', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Patient SNILS')),
                ('name', models.CharField(max_length=255, verbose_name='Patient name')),
                ('gender', models.CharField(blank=True, max_length=7, null=True, verbose_name='Patient gender')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Patient birthday')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='pat__name__idx')],
            },
        ),
    ]
