# Generated by Django 4.2.3 on 2023-07-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_patientdiagnosis'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='patientdiagnosis',
            constraint=models.UniqueConstraint(fields=('patient_snils', 'diagnosis'), name='pat_dia__snils_dia__unq'),
        ),
    ]
