# Generated by Django 4.2.3 on 2023-07-28 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_patientdiagnosis_pat_dia__snils_dia__unq'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdiagnosis',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='backend.patient', verbose_name='patient'),
        ),
    ]
