# Generated by Django 4.2.3 on 2023-07-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_patientdiagnosis_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdiagnosis',
            options={'ordering': ['patient_id'], 'verbose_name': 'Patient diagnosis', 'verbose_name_plural': 'Patients diagnoses'},
        ),
        migrations.RemoveConstraint(
            model_name='patientdiagnosis',
            name='pat_dia__snils_dia__unq',
        ),
        migrations.AddConstraint(
            model_name='patientdiagnosis',
            constraint=models.UniqueConstraint(fields=('patient_id', 'diagnosis'), name='pat_dia__snils_dia__unq'),
        ),
    ]
