# Generated by Django 4.2.3 on 2023-07-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_patientdiagnosis_diagnosis_1'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patientdiagnosis',
            name='pat_dia__snils_dia__unq',
        ),
        migrations.RemoveIndex(
            model_name='patientdiagnosis',
            name='pat_dia__diagnosis__idx',
        ),
        migrations.RemoveField(
            model_name='patientdiagnosis',
            name='diagnosis',
        ),
        migrations.AddIndex(
            model_name='patientdiagnosis',
            index=models.Index(fields=['diagnosis_1_id'], name='pat_dia__diagnosis__idx'),
        ),
        migrations.AddConstraint(
            model_name='patientdiagnosis',
            constraint=models.UniqueConstraint(fields=('patient_id', 'diagnosis_1_id'), name='pat_dia__snils_dia__unq'),
        ),
    ]
