# Generated by Django 4.2.3 on 2023-07-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_patientdiagnosis_pat_dia__snils_dia__unq_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patientdiagnosis',
            name='pat_dia__snils_dia__unq',
        ),
        migrations.RemoveIndex(
            model_name='patientdiagnosis',
            name='pat_dia__diagnosis__idx',
        ),
        migrations.RenameField(
            model_name='patientdiagnosis',
            old_name='diagnosis_1',
            new_name='diagnosis',
        ),
        migrations.AddIndex(
            model_name='patientdiagnosis',
            index=models.Index(fields=['diagnosis_id'], name='pat_dia__diagnosis__idx'),
        ),
        migrations.AddConstraint(
            model_name='patientdiagnosis',
            constraint=models.UniqueConstraint(fields=('patient_id', 'diagnosis_id'), name='pat_dia__snils_dia__unq'),
        ),
    ]
