# Generated by Django 4.2.3 on 2023-07-28 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_patientdiagnosis_pat_dia__snils_dia__unq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_snils', models.CharField(max_length=11, verbose_name='Patient SNILS')),
                ('card_type', models.CharField(max_length=3, verbose_name='Medical card type')),
                ('card_number', models.CharField(max_length=40, verbose_name='Medical card number')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_cards', to='backend.patient', verbose_name='patient')),
            ],
            options={
                'verbose_name': 'Patient medical card',
                'verbose_name_plural': 'Patients medical cards',
                'ordering': ['patient_id'],
                'indexes': [models.Index(fields=['card_number'], name='pat_car__card_number__idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='patientmedicalcard',
            constraint=models.UniqueConstraint(fields=('patient_snils', 'card_type', 'card_number'), name='pat_car__snils_t_n__unq'),
        ),
    ]
