# Generated by Django 4.2.3 on 2023-08-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_diagnosisregistry_diagnosisregistryitem_delete_semd2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPosition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Medical position code')),
                ('pid', models.IntegerField(verbose_name='Parent code')),
                ('sort', models.IntegerField(verbose_name='Sort number')),
                ('name', models.CharField(max_length=180, verbose_name='Medical position name')),
                ('equivalent', models.CharField(max_length=180, verbose_name='Medical position name equivalent')),
            ],
            options={
                'verbose_name': 'Medical position',
                'verbose_name_plural': 'Medical positions',
                'ordering': ['sort'],
            },
        ),
        # migrations.DeleteModel(
        #     name='SEMD2',
        # ),
        migrations.AddIndex(
            model_name='medicalposition',
            index=models.Index(fields=['sort'], name='med_pos__sort__idx'),
        ),
        migrations.AddIndex(
            model_name='medicalposition',
            index=models.Index(fields=['name'], name='med_pos__name__idx'),
        ),
    ]
