# Generated by Django 4.2.3 on 2023-08-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_medicalposition_delete_semd2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalposition',
            name='equivalent',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Medical position name equivalent'),
        ),
        migrations.AlterField(
            model_name='medicalposition',
            name='pid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parent code'),
        ),
        # migrations.DeleteModel(
        #     name='SEMD2',
        # ),
    ]
