# Generated by Django 4.2.3 on 2023-08-01 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_medicalposition_equivalent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SEMD2',
            new_name='SEMD'
        ),
    ]
