# Generated by Django 4.2.3 on 2023-08-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_semd_delete_semd2_semd_semd__date_time_create__idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semd',
            options={'ordering': ['date_time_create'], 'verbose_name': 'SEMD', 'verbose_name_plural': 'SEMD'},
        ),
        migrations.RenameIndex(
            model_name='semd',
            new_name='semd__date_time_create__idx',
            old_name='semd2__date_time_create__idx',
        ),
        migrations.AlterField(
            model_name='semd',
            name='medical_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semd', to='backend.medicalorganization', verbose_name='Medical organization'),
        ),
        migrations.AlterField(
            model_name='semd',
            name='medical_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semd', to='backend.medicalservice', verbose_name='Medical service'),
        ),
    ]
