# Generated by Django 4.2.3 on 2023-08-01 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_rename_patient_semd_patient_name_semd_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semd',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semd', to='backend.patient', verbose_name='Patient'),
        ),
    ]
