# Generated by Django 4.2.3 on 2023-08-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_semd_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semd',
            name='med_card_amb',
        ),
        migrations.RemoveField(
            model_name='semd',
            name='med_card_sta',
        ),
        migrations.RemoveField(
            model_name='semd',
            name='patient_birthday_str',
        ),
        migrations.RemoveField(
            model_name='semd',
            name='patient_gender',
        ),
        migrations.RemoveField(
            model_name='semd',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='semd',
            name='patient_snils',
        ),
    ]
