# Generated by Django 4.2.3 on 2023-08-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_remove_semd_condition_remove_semd_test_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semd',
            name='end_date_str',
        ),
        migrations.RemoveField(
            model_name='semd',
            name='start_date_str',
        ),
        migrations.AlterField(
            model_name='semd',
            name='place_of_service',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Place of service'),
        ),
    ]
