# Generated by Django 4.2.3 on 2023-08-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_semdtest_patient_alter_semdtest_laboratory_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semdtest',
            options={'ordering': ['patient_id', 'laboratory_test_id', 'test_time'], 'verbose_name': 'SEMD Test', 'verbose_name_plural': 'SEMD Tests'},
        ),
        migrations.AddField(
            model_name='semdtest',
            name='test_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Test date time'),
        ),
        migrations.AddIndex(
            model_name='semdtest',
            index=models.Index(fields=['patient_id', 'test_time'], name='semd_test__pat_tim__idx'),
        ),
        migrations.AddIndex(
            model_name='semdtest',
            index=models.Index(fields=['patient_id', 'laboratory_test_id', 'test_time'], name='semd_test__pat_lt_tim__idx'),
        ),
    ]
