# Generated by Django 4.2.3 on 2023-08-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_alter_semdtest_options_semdtest_test_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semdtest',
            options={'ordering': ['id'], 'verbose_name': 'SEMD Test', 'verbose_name_plural': 'SEMD Tests'},
        ),
        migrations.AddIndex(
            model_name='semd',
            index=models.Index(fields=['patient_id', 'service_time'], name='semd__pat_time__idx'),
        ),
    ]
