# Generated by Django 4.2.3 on 2023-08-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_alter_semdtest_options_semd_semd__pat_time__idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='semdtest',
            index=models.Index(fields=['test_time'], name='semd_test__time__idx'),
        ),
    ]
