# Generated by Django 4.2.3 on 2023-08-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_diagnosisregistry_medical_record_transcript_settings'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='semd',
            index=models.Index(fields=['patient_id', 'medical_service_id', 'service_time'], name='semd__pat_srv_tim__idx'),
        ),
    ]
