# Generated by Django 4.2.3 on 2023-08-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_semd_semd__pat_srv_tim__idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='semd',
            name='patient_birthday',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Patient birthday'),
        ),
        migrations.AddField(
            model_name='semd',
            name='patient_fio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Patient name'),
        ),
        migrations.AddField(
            model_name='semd',
            name='patient_gender',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Patient gender'),
        ),
        migrations.AddField(
            model_name='semd',
            name='patient_snils',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Patient SNILS'),
        ),
    ]
