# Generated by Django 4.2.3 on 2023-08-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_semd_patient_birthday_semd_patient_fio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semd',
            name='service_time_str',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Medical service date time'),
        ),
    ]
