# Generated by Django 4.2.3 on 2023-08-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_semd_service_time_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='semd',
            name='end_date_str',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Hospital end date'),
        ),
        migrations.AddField(
            model_name='semd',
            name='start_date_str',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Hospital start date'),
        ),
    ]
