# Generated by Django 4.2.3 on 2023-08-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_semd_end_date_str_semd_start_date_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='snils',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='Patient SNILS'),
        ),
        migrations.AlterField(
            model_name='semd',
            name='patient_snils',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Patient SNILS'),
        ),
    ]
