# Generated by Django 4.2.3 on 2023-08-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_alter_patient_snils_alter_semd_patient_snils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semd',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hospital end date'),
        ),
        migrations.AlterField(
            model_name='semd',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hospital start date'),
        ),
    ]
