# Generated by Django 4.2.3 on 2023-08-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_alter_semd_end_date_alter_semd_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semd',
            name='end_date_str',
        ),
        migrations.RemoveField(
            model_name='semd',
            name='patient_birthday',
        ),
        migrations.RemoveField(
            model_name='semd',
            name='patient_fio',
        ),
        migrations.RemoveField(
            model_name='semd',
            name='patient_gender',
        ),
        migrations.RemoveField(
            model_name='semd',
            name='patient_snils',
        ),
        migrations.RemoveField(
            model_name='semd',
            name='service_time_str',
        ),
        migrations.RemoveField(
            model_name='semd',
            name='start_date_str',
        ),
    ]
